---
format:
  html:
    toc: true
    smooth-scroll: true
    anchor-sections: true
    other-links:
    - text: Visit our website
      href: https://lamalab.org/
      icon: globe
    - text: Follow us on X (Twitter)
      href: https://x.com/jablonkagroup
      icon: twitter-x
    - text: We are hiring!
      href: https://forms.fillout.com/t/eoGA7AhnAKus
      icon: person-badge
    - text: Contact us
      href: mailto:contact@lamalab.org
      icon: mailbox
acronyms:
  insert_loa: false 
  insert_links: false  
  fromfile: ./acronyms.yml
---


# General purpose models for the chemical sciences {.unnumbered}

## Abstract

Data-driven techniques have a large potential to transform and accelerate the chemical sciences. 
    However, chemical sciences also pose the unique challenge of very diverse, small, fuzzy datasets that are difficult to leverage in conventional machine learning approaches completely. 
    A new class of models, general-purpose models (GPMs) such as large language models, have shown the ability to solve tasks they have not been directly trained on, and to flexibly operate with low amounts of data in different formats.
    In this review, we discuss fundamental building principles of GPMs and review recent applications of those models in the chemical sciences across the entire scientific process.
    While many of these applications are still in the prototype phase, we expect that the increasing interest in GPMs will make many of them mature in the coming years.

## Acknowledgments

This work was supported by the Carl-Zeiss Foundation. 

A.A.\ acknowledges financial support for this research by the Fulbright U.S. Student Program, which is sponsored by the U.S. Department of State and the German-American Fulbright Commission. Its contents are solely the responsibility of the author and do not necessarily represent the official views of the Fulbright Program, the Government of the United States, or the German-American Fulbright Commission. 
 
M. S.-W.\ was supported by Intel and Merck via the AWASES research center. 

A.M.'s work was funded by the SOL-AI project, funded as part of the Helmholtz Foundation Model Initiative of the Helmholtz Association. 

G.P.'s work was supported by the HPC Gateway measure of the Helmholtz Association.

K.M.J.\ is part of the NFDI consortium FAIRmat funded by the Deutsche Forschungsgemeinschaft (DFG, German Research Foundation) - project 460197019.

We thank Mimi Lavin and Maximilian Greiner for their feedback on a draft of this article.

## Author contributions

N. A. was the lead contributor for the [Building Principles of GPMs](03-architectures.qmd) section. Including its writing and figures (excluding the [Model Level Adaptation](03-architectures.qmd#sec:model_adaptation) subsection). N. A. also reviewed the [Introduction](01-introduction.qmd), [The Shape and Structure of Chemical Data](02-data_taxonomy.qmd), [Evaluations](04-evals.qmd), [Implications of GPMs: Education, Safety, and Ethics](07-safety.qmd), and [Property Prediction](05-applications.qmd#sec:prediction) and [Molecular and Material Generation](05-applications.qmd#sec:mol_generation) sections.

A. A. was the primary contributor to the writing of the [Property Prediction](05-applications.qmd#sec:prediction), [Molecular and Material Generation](05-applications.qmd#sec:mol_generation), [Safety](07-safety.qmd#sec:safety), and [Ethics](07-safety.qmd#sec:ethics) sections, conceptualized the outline for safety and ethics sections, designed and created all figures/schematics/plots in sections with primary contribution, was one of the contributors to the [AI Scientists](05-applications.qmd#sec:ai-scientists) overview, edited [Introduction](01-introduction.qmd), [Evaluations](04-evals.qmd), [Building Principles of GPMs](03-architectures.qmd), [Knowledge Gathering](05-applications.qmd#sec:information_gathering), [Experiment Execution](05-applications.qmd#sec:experiment_execution), and [Education](07-safety.qmd#sec:education) sections.

M.R.-G. was the primary contributor to the [AI Scientists](05-applications.qmd#sec:ai-scientists) overview, the [Hypothesis Generation](05-applications.qmd#sec:hypothesis), and the [LLMs as Optimizers](05-applications.qmd#sec:optimizers) sections, and helped in reviewing the entire manuscript.

A.M. was the main contributor to the [Introduction](01-introduction.qmd) and [The Shape and Structure of Chemical Data](02-data_taxonomy.qmd) sections, and the main contributor to the [Knowledge Gathering](05-applications.qmd#sec:information_gathering) and [Reporting](05-applications.qmd#sec:reporting) sections within the applications section, with minor contributions to the [Building Principles of GPMs](03-architectures.qmd) and the [Safety](07-safety.qmd#sec:safety) sections. Has drafted the initial outline of the article. Reviewed the [Building Principles of GPMs](03-architectures.qmd) sections, the [Safety](07-safety.qmd#sec:safety) section, the [Hypothesis Generation](05-applications.qmd#sec:hypothesis), the [Data Analysis](05-applications.qmd#sec:data_analysis) sections and contributed to the review of the [LLMs as Optimizers](05-applications.qmd#sec:optimizers) section.

M.S.-W. was the main contributor to the [Evaluations](04-evals.qmd), [Education](07-safety.qmd#sec:education) and [Data Analysis](05-applications.qmd#sec:data_analysis) section. M.S.-W. also reviewed the [The Shape and Structure of Chemical Data](02-data_taxonomy.qmd), [Hypothesis Generation](05-applications.qmd#sec:hypothesis), [Experiment Execution](05-applications.qmd#sec:experiment_execution), [Reporting](05-applications.qmd#sec:reporting) and [Safety](07-safety.qmd#sec:safety) section. Unified all figures. Kept track of upcoming deadlines.

A.A.A. was the main contributor to the [Experiment Execution](05-applications.qmd#sec:experiment_execution) section, including its figure, and a minor contributor to the post-training subsection. A.A.A. reviewed the [Introduction](01-introduction.qmd), [Experiment Planning](05-applications.qmd#sec:planning), [Molecular and Material Generation](05-applications.qmd#sec:mol_generation) and [Education](07-safety.qmd#sec:education) sections, edited [The Shape and Structure of Chemical Data](02-data_taxonomy.qmd) and [Building Principles of GPMs](03-architectures.qmd) sections, created the glossary, and ensured that most references are accessible via a DOI.

M. S. was the primary contributor to the writing of [Experiment Planning](05-applications.qmd#sec:planning) section and related figure. And also helped in reviewing [Knowledge Gathering](05-applications.qmd#sec:information_gathering), [Property Prediction](05-applications.qmd#sec:prediction), and [LLMs as Optimizers](05-applications.qmd#sec:optimizers) sections.

G.P. was the main contributor to [Model Level Adaptation](03-architectures.qmd#sec:model_adaptation) section, including its writing and table. G.P. additionally reviewed the [The Shape and Structure of Chemical Data](02-data_taxonomy.qmd), [Data Analysis](05-applications.qmd#sec:data_analysis), [Reporting](05-applications.qmd#sec:reporting) and [Molecular and Material Generation](05-applications.qmd#sec:mol_generation) sections.

K.M.J. initiated and led the project. K.M.J. edited all sections. 

## Conflicts of Interest
K.M.J.\ has been a paid contractor for OpenAI as part of the Red-Teaming Network.

## Citation

If you find this work useful, please cite it using:

```bibtex
@article{alampara2025general,
  title   = {General purpose models for the chemical sciences},
  author  = {Nawaf Alampara and Anagha Aneesh and Martiño Ríos-García and Adrian Mirza and Mara Schilling-Wilhelmi and Ali Asghar Aghajani and Meiling Sun and Gordan Prastalo and Kevin Maik Jablonka},
  year    = {2025},
  journal = {arXiv preprint arXiv: 2507.07456}
}
```

---

## Table of Contents

This book covers the following topics:

1. [Introduction](01-introduction.qmd)
2. [The Shape and Structure of Chemical Data](02-data_taxonomy.qmd)
3. [Building Principles of GPMs](03-architectures.qmd)
4. [Evaluations](04-evals.qmd)
5. [Applications](05-applications.qmd)
6. [Accelerating Applications](06-accelerating_applications.qmd)
7. [Implications of GPMs: Education, Safety, and Ethics](07-safety.qmd)
8. [Outlook and Conclusions](08-outlook_conclusions.qmd)
-  [References](09-references.qmd)
