---
format:
  html:
    toc: true
    smooth-scroll: true
    anchor-sections: true
    other-links:
    - text: Visit our website
      href: https://lamalab.org/
      icon: globe
    - text: Follow us on X (Twitter)
      href: https://x.com/jablonkagroup
      icon: twitter-x
    - text: We are hiring!
      href: https://forms.fillout.com/t/eoGA7AhnAKus
      icon: person-badge
    - text: Contact us
      href: mailto:contact@lamalab.org
      icon: mailbox
acronyms:
  insert_loa: false 
  insert_links: false  
  fromfile: ./acronyms.yml
---

# How to Learn Things Using LLMs {.unnumbered}

LLMs can often help make the process of learning new materials easier and more enjoyable. 
They can help in different stages of learning such as gatehring materials, creating a learning plan, clarifying and reviewing topics, and even testing what you have learned.

::: {.callout-tip}
## Be Specific!

As a general rule, try to be specific in your requests from the LLM. You will get responses that are more tailored to your needs if you are clear what you are looking for. For example, "Help me learn machine learning" will not result in a very helpful response, but it's more likely that "What is the difference between L1 and L2 regularization?" will. 
:::


## Getting Started

### Gathering Learning Materials

Since chatbots are powered by generalist LLMs, they have a good general knowledge about standard textbooks and curricula for different disciplines.
If you are completely new to a field and want to start learning, you can ask an LLM for the important starting topics and popular learning materials in that field.
You will get better results if you include your current level of knowledge and/or background in the prompt and what you are hoping to achieve (e.g. doing a deep-dive or just getting familiar with the field). 
We recomend prompting the LLM twice: once without any web-search and once with web-search enabled. The reason is that you will often get slightly different results. The web-search is more biased towards online forums such as Reddit and will point to towards more "popular" resources, while the response without web-search will often point towards "classics". If you see the same resource in both responses, it's usually a good one!
Once you find a few resources and want to decide which one to use, you can ask the LLM to give you a list of differences or pros and cons for each resource. 
In addition to more traditional resources like textbooks, you can also try to look for online lectures or YouTube videos.

### Creating a Learning Plan

Sometimes you know what you want to learn but you don't know where/how to begin. You can ask an LLM to help create a structured learning plan for you. It will often start at the beginner-friendly topics and progressively get into more advanced topics.


## During the Process

So far we have only used the LLM to point us towards the right materials. So we are mostly safe from hallucinations! 
Things get more tricky when you want to directly access the LLMs knowlege. The more "advanced" your question is, the more likely it is for the LLM to hallucinate and give you a wrong answer.

::: {.callout-tip}

## "Advanced?"
Of course, "advanced" is a relative term. In general, LLMs perform much better on "knowledge-based" questions, meaning things that you will find in standard textbooks. For scientific questions, if your question does not need a high level of reasoning and you think that an average undergraduate student in the field *should* be able to answer your question, it is very likely (although there's no guarantee!) that the LLM can also answer that question.
:::

### Clarifications

One of the advantages of using an LLM to learn, is that you can ask clarification questions. Instead of relying on the LLM for everything, it is more useful to refer to it once you have a specific question. "*I don't understand why X is ...*", "*I know X and Y but I'm confused about Z*", and "*What is the point of X?*" are examples of types of clarification questions you can ask.


### Contrastive Learning

Another useful way to leverage the LLM's knowlege is to ask it to contrast and compare two different things/topics/methods/etc. Some examples are "*What is the difference between X and Y?*", "*How is X related to Y?"*, *"What's the point of X if can just do Y?"*, "*What are the advantages and disadvantages for each of these methods?*"

### Have Fun With It!

LLMs allow you to learn how you want to learn. You can use this to make the process more fun for you. This is specially true for language learning: one of us actually asked ChatGPT to creat a text-based choose-your-own-adventure style game in German to help them learn the language! It started something like this: "*Es ist Mitternacht. Du stehst auf einem Marktplatz ohne Häuser. Der Boden ist ein Schachbrett...*"


## Get Feedback

Once you have done some learning, you can use the LLM to create quick summaries or cheatsheets for you. You can also ask it to quiz you on something. "*I'm learning organic chemistry and I just learned about aromatic compouds. Ask me questions about it to help me learn better.*"

## One Big Caveat

It is very important to remember that ***LLMs can make mistakes!*** For sensitive tasks, always double check what you are getting out of the LLM with a reliable source.